<div class="container main-content">
  <div class="row">
    <div class="span8">
      <?php
        $flashMessenger = $this->flashMessenger();
        foreach($flashMessenger->getMessages() as $message) {
          echo '<h3 class="zf-green">' . $message . '</h3>';
        }
      ?>

    <ul class="nav nav-tabs">
      <li class="active"><a href="#submitted" data-toggle="tab">Submitted Modules</a></li>
      <li><a href="#owned" data-toggle="tab">My Modules</a></li>
      <li><a href="#collaborations" data-toggle="tab">My Collaborations</a></li>
    </ul>

    <div class="tab-content">
    <div class="tab-pane active" id="submitted">
<?php
    $modules = $this->listModules(array('user' => true, 'sort' => true));
    if (empty($modules)) { ?>
    <div class="alert alert-block">No modules was submitted yet</div>
    <?php
    } else {
        foreach($modules as $type => $moduleArray) {
            if (!empty($moduleArray)) {
                echo '<section><header class="navbar-inner">' .
                    '<h2 class="pull-left">' . $type . '</h2>' .
                    '<i class="icon-minus"></i>' .
                    '</header><div class="section-list">';
                foreach($moduleArray as $module) {
                    echo $this->listModuleHtml(
                        array(
                            'picture' => $module->getPhotoUrl(),
                            'owner' => $module->getOwner(),
                            'url' => $module->getUrl(),
                            'action' => $this->url('module/remove_module'),
                            'moduleName' => $module->getName(),
                            'createdAt' => $module->getCreatedAt(),
                            'returnUrl' => $module->getUrl(),
                            'description' => $module->getDescription(),
                            'submitValue' => 'Remove',
                            'submitBtnClass' => 'btn-danger',
                        )
                    );
                }
                echo '</div></section>';
            }
        }
    }
?>
  </div>
  <div class="tab-pane" id="owned">
    <?php
    $repositories = $this->userRepositories(array('sort' => true));

    if (empty($repositories)) { ?>
    <div class="alert alert-block">No public and not forked repositories found</div>
    <?php
    }else {
        $owned = $repositories['owned'];
        foreach($owned as $module) {
            $owner = $module->getOwner();
            echo $this->listModuleHtml(
              array(
                'picture' => $owner['avatar_url'],
                'owner' => $owner['login'],
                'url' => $module->getUrl(),
                'action' => $this->url('module/add_module'),
                'moduleName' => $module->getName(),
                'createdAt' => $module->getCreatedAt(),
                'returnUrl' => $module->getHtmlUrl(),
                'description' => $module->getDescription(),
                'submitValue' => 'Submit',
                'submitBtnClass' => 'btn-success',
              )
            );
        }
    }
?>
  </div>
  <div class="tab-pane" id="collaborations">
    <?php
    if (empty($repositories)) { ?>
    <div class="alert alert-block">No public and not forked repositories found</div>
    <?php
    } else {
        $collaborations = $repositories['collaborations'];
        foreach($collaborations as $module) {
            $owner = $module->getOwner();
            echo $this->listModuleHtml(
                array(
                    'picture' => $owner['avatar_url'],
                    'owner' => $owner['login'],
                    'url' => $module->getUrl(),
                    'action' => $this->url('module/add_module'),
                    'moduleName' => $module->getName(),
                    'createdAt' => $module->getCreatedAt(),
                    'returnUrl' => $module->getHtmlUrl(),
                    'description' => $module->getDescription(),
                    'submitValue' => 'Submit',
                    'submitBtnClass' => 'btn-success',
                )
            );
        }
    }
?>
  </div>
</div>


  </div>
  <div class="span4">
    <div class="sidebar">
      <h3 style="text-align:center">Hello, <?php echo $this->zfcUserDisplayName(); ?>!</h3>
      <img class="thumbnail" src="<?php
          echo $this->zfcUserIdentity()->getPhotoUrl();
      ?>" alt="<?php echo $this->zfcUserDisplayName(); ?>"/>
      <br/>
    </div>
  </div>
</div>
</div>