<div class="container-fluid landing-intro">
  <div class="container">
    <div id="header-intro" class="row">
      <div class="span8">
        <h1 class="zf-green">
          Welcome to the ZF2 Modules Site
          <br />
          <small>
            Some awesome sentence about modules
          </small>
        </h1>
        <p>
         This website is a work-in-progress. In the future you will be able to use this website to browse, search, rate, and comment on all of the great modules the Zend Framework community has to offer.
          <hr />
        <blockquote>
          <p>
            <em>
              Hell, we might even throw in something cheesy like a hipster quote.
            </em>
          </p>
          <small>
            Someone idiot
            <cite title="Source Title">
              Hipster
            </cite>
          </small>
        </blockquote>
    </div>
    <div class="span4">
      <img class="attentionimage pull-right" src="img/rsz_logo.png" />
    </div>
  </div>
</div>
  <div id="toggleHeader">
    <img id="closedLogo" class="attentionimage" src="img/zend-logo_small.png" />
    <p class="toggledTitle">Modules</p>
    <form class="toggledSearch">
      <input type="text" class="search-query span6" placeholder="Type to start searching...">
    </form>
    <p class="pull-right"><i class="icon-upload"></i> Toggle this header...</p>
  </div>
</div>



<div class="container main-content">
  <div class="row">
    <div class="span8">
      <div class="row-fluid">
        <div class="span12">
          <div class="navbar">
            <div class="navbar-inner">
              <h1 class="zf-green">Avilable Modules</h1>
              <p>Select which module you want to Submit for Listing</p>
            </div>
          </div>
        </div>
      </div>
      <?php
        $flashMessenger = $this->flashMessenger();
        foreach($flashMessenger->getMessages() as $message) {
          echo '<h3 class="zf-green">' . $message . '</h3>';
        }
      ?>

    <ul class="nav nav-tabs">
      <li class="active"><a href="#submitted" data-toggle="tab">Submitted Modules</a></li>
      <li><a href="#owned" data-toggle="tab">My Modules</a></li>
      <li><a href="#collaborations" data-toggle="tab">My Collaborations</a></li>
    </ul>

    <div class="tab-content">
    <div class="tab-pane active" id="submitted">
<?php
    $modules = $this->listModules(array('user' => true, 'sort' => true));
    if (empty($modules)) { ?>
    <div class="alert alert-block">No modules was submitted yet</div>
    <?php
    } else {
        foreach($modules as $type => $moduleArray) {
            if (!empty($moduleArray)) {
                echo '<section class="navbar-inner">' .
                    '<header><h2>' . $type . '</h2></header>';
                foreach($moduleArray as $module) {
                    echo $this->listModuleHtml(
                        array(
                            'picture' => $module->getPhotoUrl(),
                            'owner' => $module->getOwner(),
                            'url' => $module->getUrl(),
                            'action' => $this->url('module/remove_module'),
                            'moduleName' => $module->getName(),
                            'createdAt' => $module->getCreatedAt(),
                            'returnUrl' => $module->getUrl(),
                            'description' => $module->getDescription(),
                            'submitValue' => 'Remove',
                            'submitBtnClass' => 'btn-danger',
                        )
                    );
                }
                echo '</section>';
            }
        }
    }
?>
  </div>
  <div class="tab-pane" id="owned">
    <?php
    $repositories = $this->userRepositories(array('sort' => true));

    if (empty($repositories)) { ?>
    <div class="alert alert-block">No public and not forked repositories found</div>
    <?php
    }else {
        $owned = $repositories['owned'];
        foreach($owned as $module) {
            $owner = $module->getOwner();
            echo $this->listModuleHtml(
              array(
                'picture' => $owner['avatar_url'],
                'owner' => $owner['login'],
                'url' => $module->getUrl(),
                'action' => $this->url('module/add_module'),
                'moduleName' => $module->getName(),
                'createdAt' => $module->getCreatedAt(),
                'returnUrl' => $module->getHtmlUrl(),
                'description' => $module->getDescription(),
                'submitValue' => 'Submit',
                'submitBtnClass' => 'btn-success',
              )
            );
        }
    }
?>
  </div>
  <div class="tab-pane" id="collaborations">
    <?php
    if (empty($repositories)) { ?>
    <div class="alert alert-block">No public and not forked repositories found</div>
    <?php
    } else {
        $collaborations = $repositories['collaborations'];
        foreach($collaborations as $module) {
            $owner = $module->getOwner();
            echo $this->listModuleHtml(
                array(
                    'picture' => $owner['avatar_url'],
                    'owner' => $owner['login'],
                    'url' => $module->getUrl(),
                    'action' => $this->url('module/add_module'),
                    'moduleName' => $module->getName(),
                    'createdAt' => $module->getCreatedAt(),
                    'returnUrl' => $module->getHtmlUrl(),
                    'description' => $module->getDescription(),
                    'submitValue' => 'Submit',
                    'submitBtnClass' => 'btn-success',
                )
            );
        }
    }
?>
  </div>
</div>


  </div>
  <div class="span4">
    <div class="sidebar">
      <h3 style="text-align:center">Hello, <?php echo $this->zfcUserDisplayName(); ?>!</h3>
      <img class="thumbnail" src="<?php
          echo $this->zfcUserIdentity()->getPhotoUrl();
      ?>" alt="<?php echo $this->zfcUserDisplayName(); ?>"/>
      <br/>
    </div>
  </div>
</div>
